# Tomcat
server:
 tomcat:
  uri-encoding: UTF-8
  max-threads: 1000
  min-spare-threads: 30
 port: 8080
 connection-timeout: 5000ms
#https:
#  port: 8443
#  ssl:
#    key-store: classpath:sample.jks
#    key-store-password: secret
#    key-password: password
#spring
spring:
 # 环境 dev|test|pro
 profiles:
  active: dev
 application:
  name: bee-cloud-java
 servlet:
  multipart:
   max-file-size: 100MB
   max-request-size: 1000MB
#mybatisPlus
mybatis-plus:
 mapper-locations: classpath:mapper/**/*.xml
 #实体扫描，多个package用逗号或者分号分隔
 typeAliasesPackage: com.hutu.modules
 global-config:
  banner: false
  db-config:
   #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
   id-type: AUTO
   #序列接口实现类配置
   #key-generator: com.baomidou.springboot.xxx
   #逻辑删除配置
   logic-delete-value: 1
   logic-not-delete-value: 0
   #自定义填充策略接口实现
   #meta-object-handler: com.baomidou.springboot.xxx
 configuration:
  map-underscore-to-camel-case: false
  cache-enabled: false
  call-setters-on-nulls: true