# 附件上传路径配置
web:
  upload-path: D:\upload\
  url-path: http://192.168.3.42:${server.port}/
# DataSource Config
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://122.51.118.51:3306/hlwcbz_dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
#swagger配置参考： https://github.com/SpringForAll/spring-boot-starter-swagger
swagger:
  enabled: true
  title: 管理系统api文档
  authorization:
    key-name: token
  version: 1.0.0
  base-package: com.hutu.modules
  base-path: /**
  exclude-path: /error, /ops/**
# 日志
logging:
  #  生成日志文件名称
  file: ${spring.application.name}
  #  日志文件输出目录，没有会自动生成目录
  path: ./logs
# 缓存设置
jetcache:
  statIntervalMinutes: 0
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379
ws:
  server:
    port: 8081
    host: 192.168.3.93