# 附件上传路径配置
web:
  upload-path: D:\upload\
  url-path: http://192.168.3.42:${server.port}/
# DataSource Config
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://122.51.118.51:3306/followup-dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: qwert123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
#swagger配置参考： https://github.com/SpringForAll/spring-boot-starter-swagger
swagger:
  enabled: true
  title: 管理系统api文档
  authorization:
    key-name: token
  version: 1.0.0
  base-package: com.hutu.modules
  base-path: /**
  exclude-path: /error, /ops/**
# 日志
logging:
  #  生成日志文件名称
  file: ${spring.application.name}
  #  日志文件输出目录，没有会自动生成目录
  path: ./logs
# 缓存设置
jetcache:
  statIntervalMinutes: 0
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379
ws:
  server:
    port: 8081
    host: 192.168.3.93

#捷微微信管理后台接口配置
jeewx:
#  domain: http://iullor.utools.club   #域名
#  domain: http://zyzjeewx.utools.club/wechat
  domain: http://hutu.utools.club/wechat
  public: http://yunfeng_medical_chain.gitee.io/patient_form_development/#/userForm   #码云地址
  qrcode:   #二维码
    create: ${jeewx.domain}/followup/createQrcode/
    expiredTime: 1000 #过期时间
  followUp:
    template:
      send: ${jeewx.domain}/followup/template/send  #发送随访表单的接口
      goUrl: ${jeewx.public}      #模板要跳转的地址
#      templateId1: x6AA9SrxSQ3Al9H3Ihhk8Syy5R1rawE_bz5xOp9W8vI #胡图的测试号模板id
#      templateId1: 1P0L1ekD1oxpVSaQhqi2ThzBY34WdTWmYPxpJTMGqCs #线上的id
      templateId1: iXMb5V2Zj7f-FkAb6-oHmHsXUygusmEIUEVidZPDLek #寒冷无处不在测试号的模板id
